// =============================================================================
// CodeGenerator — Roslyn-powered source code generation from templates.
// =============================================================================
// Generates C# source files from templates and metadata. Used by the CLI to:
//   1. Scaffold new adapter implementations from port interfaces
//   2. Generate DTOs from domain models
//   3. Generate test stubs from existing classes
//   4. Generate mock implementations for ports
//   5. Generate controller scaffolds from port interfaces
//   6. Generate documentation stubs (defers to DocGen for full XML doc)
//
// Generation Strategy:
//   - Parse existing port interfaces via Roslyn SyntaxTree
//   - Extract method signatures, parameter types, return types
//   - Apply template to generate implementing class
//   - Format output via Roslyn Formatter
//   - Write to target project directory
//
// Templates are inline (not file-based) to keep the CLI self-contained.
// For complex generation, use the ClaudeCodeBridge to generate via AI.
//
// Example:
//   var gen = new CodeGenerator(solutionRoot);
//   // Generate a Mock adapter for IEvidencePort
//   await gen.GenerateAdapterAsync("IEvidencePort", "Mock", ct);
//   // Generate a test class for EvidenceController
//   await gen.GenerateTestStubAsync("EvidenceController", ct);
//   // Scaffold a new port interface + mock adapter
//   await gen.ScaffoldPortAsync("IAlertPort", new[] { "Task SendAlertAsync(..." }, ct);
//
// WAL: Generated files include a header comment marking them as auto-generated.
//      Roslyn SyntaxFactory could replace string templates, but string templates
//      are more readable for this use case and easier to modify.
// =============================================================================

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Formatting;

namespace TheWatch.Cli.Services.Roslyn;

public class CodeGenerator
{
    private readonly string _solutionRoot;

    public CodeGenerator(string solutionRoot)
    {
        _solutionRoot = solutionRoot;
    }

    /// <summary>
    /// Generate a mock adapter class implementing a port interface.
    /// Reads the port .cs file, extracts method signatures, writes the mock.
    /// </summary>
    public async Task<GenerationResult> GenerateAdapterAsync(
        string portInterfaceName,
        string adapterName,
        CancellationToken ct = default)
    {
        // Find the port interface file
        var portFile = FindPortFile(portInterfaceName);
        if (portFile is null)
            return GenerationResult.Fail($"Port interface '{portInterfaceName}' not found");

        var source = await File.ReadAllTextAsync(portFile, ct);
        var tree = CSharpSyntaxTree.ParseText(source);
        var root = await tree.GetRootAsync(ct);

        var iface = root.DescendantNodes()
            .OfType<InterfaceDeclarationSyntax>()
            .FirstOrDefault(i => i.Identifier.Text == portInterfaceName);

        if (iface is null)
            return GenerationResult.Fail($"Interface '{portInterfaceName}' not found in {portFile}");

        // Extract methods
        var methods = iface.Members.OfType<MethodDeclarationSyntax>().ToList();
        var className = $"{adapterName}{portInterfaceName[1..]}"; // IFooPort → MockFooPort
        var ns = $"TheWatch.Adapters.{adapterName}";
        var targetDir = Path.Combine(_solutionRoot, $"TheWatch.Adapters.{adapterName}");

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// =============================================================================");
        sb.AppendLine($"// {className} — Auto-generated {adapterName} adapter for {portInterfaceName}");
        sb.AppendLine("// =============================================================================");
        sb.AppendLine($"// Generated by TheWatch.Cli CodeGenerator at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen");
        sb.AppendLine("// =============================================================================");
        sb.AppendLine();
        sb.AppendLine("using TheWatch.Shared.Domain.Ports;");
        sb.AppendLine("using TheWatch.Shared.Domain.Models;");
        sb.AppendLine("using TheWatch.Shared.Enums;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"public class {className} : {portInterfaceName}");
        sb.AppendLine("{");

        foreach (var method in methods)
        {
            var returnType = method.ReturnType.ToString();
            var methodName = method.Identifier.Text;
            var parameters = string.Join(", ", method.ParameterList.Parameters.Select(p => $"{p.Type} {p.Identifier}"));
            var paramNames = method.ParameterList.Parameters.Select(p => p.Identifier.Text).ToList();

            sb.AppendLine($"    /// <summary>{adapterName} implementation of {portInterfaceName}.{methodName}</summary>");
            sb.AppendLine($"    public {(method.Modifiers.Any(SyntaxKind.AsyncKeyword) ? "async " : "")}{returnType} {methodName}({parameters})");
            sb.AppendLine("    {");

            // Generate stub body based on return type
            if (returnType == "Task")
            {
                sb.AppendLine($"        // TODO: Implement {adapterName}-specific logic");
                sb.AppendLine("        await Task.CompletedTask;");
            }
            else if (returnType.StartsWith("Task<"))
            {
                var innerType = returnType[5..^1]; // Task<Foo> → Foo
                sb.AppendLine($"        // TODO: Implement {adapterName}-specific logic");
                sb.AppendLine($"        return await Task.FromResult<{innerType}>(default!);");
            }
            else if (returnType == "void")
            {
                sb.AppendLine($"        // TODO: Implement {adapterName}-specific logic");
            }
            else
            {
                sb.AppendLine($"        // TODO: Implement {adapterName}-specific logic");
                sb.AppendLine($"        return default!;");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        // Format with Roslyn
        var formatted = FormatCode(sb.ToString());

        // Write file
        var outputPath = Path.Combine(targetDir, $"{className}.cs");
        Directory.CreateDirectory(targetDir);
        await File.WriteAllTextAsync(outputPath, formatted, ct);

        return GenerationResult.Ok(outputPath, className, methods.Count);
    }

    /// <summary>
    /// Generate a test stub class for an existing class.
    /// </summary>
    public async Task<GenerationResult> GenerateTestStubAsync(
        string className,
        CancellationToken ct = default)
    {
        // Find the class file
        var classFile = FindClassFile(className);
        if (classFile is null)
            return GenerationResult.Fail($"Class '{className}' not found in solution");

        var source = await File.ReadAllTextAsync(classFile, ct);
        var tree = CSharpSyntaxTree.ParseText(source);
        var root = await tree.GetRootAsync(ct);

        var classDecl = root.DescendantNodes()
            .OfType<ClassDeclarationSyntax>()
            .FirstOrDefault(c => c.Identifier.Text == className);

        if (classDecl is null)
            return GenerationResult.Fail($"Class '{className}' not found in {classFile}");

        var publicMethods = classDecl.Members
            .OfType<MethodDeclarationSyntax>()
            .Where(m => m.Modifiers.Any(SyntaxKind.PublicKeyword))
            .ToList();

        var testClassName = $"{className}Tests";
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// =============================================================================");
        sb.AppendLine($"// {testClassName} — Auto-generated test stubs for {className}");
        sb.AppendLine($"// Generated at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("// =============================================================================");
        sb.AppendLine();
        sb.AppendLine("using Xunit;");
        sb.AppendLine();
        sb.AppendLine("namespace TheWatch.Shared.Tests;");
        sb.AppendLine();
        sb.AppendLine($"public class {testClassName}");
        sb.AppendLine("{");

        foreach (var method in publicMethods)
        {
            var methodName = method.Identifier.Text;
            sb.AppendLine("    [Fact]");
            sb.AppendLine($"    public async Task {methodName}_ShouldReturnExpectedResult()");
            sb.AppendLine("    {");
            sb.AppendLine("        // Arrange");
            sb.AppendLine($"        // TODO: Set up {className} with mock dependencies");
            sb.AppendLine();
            sb.AppendLine("        // Act");
            sb.AppendLine($"        // TODO: Call {methodName} with test parameters");
            sb.AppendLine();
            sb.AppendLine("        // Assert");
            sb.AppendLine("        Assert.True(true); // TODO: Add real assertions");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        var formatted = FormatCode(sb.ToString());
        var outputPath = Path.Combine(_solutionRoot, "TheWatch.Shared.Tests", $"{testClassName}.cs");
        await File.WriteAllTextAsync(outputPath, formatted, ct);

        return GenerationResult.Ok(outputPath, testClassName, publicMethods.Count);
    }

    /// <summary>
    /// Scaffold a new port interface + mock adapter pair.
    /// </summary>
    public async Task<List<GenerationResult>> ScaffoldPortAsync(
        string portInterfaceName,
        string[] methodSignatures,
        CancellationToken ct = default)
    {
        var results = new List<GenerationResult>();

        // Validate name
        if (!portInterfaceName.StartsWith("I"))
            portInterfaceName = "I" + portInterfaceName;
        if (!portInterfaceName.EndsWith("Port"))
            portInterfaceName += "Port";

        // Generate port interface
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// =============================================================================");
        sb.AppendLine($"// {portInterfaceName} — Auto-generated port interface");
        sb.AppendLine($"// Generated at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("// =============================================================================");
        sb.AppendLine();
        sb.AppendLine("namespace TheWatch.Shared.Domain.Ports;");
        sb.AppendLine();
        sb.AppendLine($"public interface {portInterfaceName}");
        sb.AppendLine("{");

        foreach (var sig in methodSignatures)
        {
            sb.AppendLine($"    {sig.TrimEnd(';')};");
        }

        sb.AppendLine("}");

        var portPath = Path.Combine(_solutionRoot, "TheWatch.Shared", "Domain", "Ports", $"{portInterfaceName}.cs");
        var formatted = FormatCode(sb.ToString());
        await File.WriteAllTextAsync(portPath, formatted, ct);
        results.Add(GenerationResult.Ok(portPath, portInterfaceName, methodSignatures.Length));

        // Generate mock adapter
        await File.WriteAllTextAsync(portPath, formatted, ct); // Ensure port exists before adapter gen reads it
        var adapterResult = await GenerateAdapterAsync(portInterfaceName, "Mock", ct);
        results.Add(adapterResult);

        return results;
    }

    /// <summary>
    /// Generate a DTO from a domain model (strips navigation properties, adds JSON attributes).
    /// </summary>
    public async Task<GenerationResult> GenerateDtoAsync(
        string modelClassName,
        CancellationToken ct = default)
    {
        var classFile = FindClassFile(modelClassName);
        if (classFile is null)
            return GenerationResult.Fail($"Model class '{modelClassName}' not found");

        var source = await File.ReadAllTextAsync(classFile, ct);
        var tree = CSharpSyntaxTree.ParseText(source);
        var root = await tree.GetRootAsync(ct);

        var classDecl = root.DescendantNodes()
            .OfType<ClassDeclarationSyntax>()
            .FirstOrDefault(c => c.Identifier.Text == modelClassName);

        if (classDecl is null)
            return GenerationResult.Fail($"Class '{modelClassName}' not found in {classFile}");

        var properties = classDecl.Members
            .OfType<PropertyDeclarationSyntax>()
            .Where(p => p.Modifiers.Any(SyntaxKind.PublicKeyword))
            .ToList();

        var dtoName = $"{modelClassName}Dto";
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"// Auto-generated DTO for {modelClassName}");
        sb.AppendLine($"// Generated at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace TheWatch.Shared.Dtos;");
        sb.AppendLine();
        sb.AppendLine($"public class {dtoName}");
        sb.AppendLine("{");

        foreach (var prop in properties)
        {
            var type = prop.Type.ToString();
            var name = prop.Identifier.Text;

            // Skip navigation properties (List<T> where T is a domain model)
            if (type.StartsWith("List<") && !type.Contains("string"))
                continue;

            sb.AppendLine($"    [JsonPropertyName(\"{char.ToLowerInvariant(name[0])}{name[1..]}\")]");
            sb.AppendLine($"    public {type} {name} {{ get; set; }}");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        var formatted = FormatCode(sb.ToString());
        var outputPath = Path.Combine(_solutionRoot, "TheWatch.Shared", "Dtos", $"{dtoName}.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        await File.WriteAllTextAsync(outputPath, formatted, ct);

        return GenerationResult.Ok(outputPath, dtoName, properties.Count);
    }

    // ── Helpers ─────────────────────────────────────────────────────

    private string? FindPortFile(string interfaceName)
    {
        var portsDir = Path.Combine(_solutionRoot, "TheWatch.Shared", "Domain", "Ports");
        if (!Directory.Exists(portsDir)) return null;
        return Directory.GetFiles(portsDir, "*.cs", SearchOption.AllDirectories)
            .FirstOrDefault(f => File.ReadAllText(f).Contains($"interface {interfaceName}"));
    }

    private string? FindClassFile(string className)
    {
        return Directory.GetFiles(_solutionRoot, "*.cs", SearchOption.AllDirectories)
            .Where(f => !f.Contains("obj") && !f.Contains("bin"))
            .FirstOrDefault(f =>
            {
                try { return File.ReadAllText(f).Contains($"class {className}"); }
                catch { return false; }
            });
    }

    private static string FormatCode(string code)
    {
        try
        {
            var tree = CSharpSyntaxTree.ParseText(code);
            var root = tree.GetRoot();
            var workspace = new AdhocWorkspace();
            var formatted = Formatter.Format(root, workspace);
            return formatted.ToFullString();
        }
        catch
        {
            return code; // return unformatted if Roslyn formatter fails
        }
    }
}

public class GenerationResult
{
    public bool Success { get; set; }
    public string? OutputPath { get; set; }
    public string? GeneratedTypeName { get; set; }
    public int MembersGenerated { get; set; }
    public string? ErrorMessage { get; set; }

    public static GenerationResult Ok(string path, string typeName, int members) => new()
    {
        Success = true,
        OutputPath = path,
        GeneratedTypeName = typeName,
        MembersGenerated = members
    };

    public static GenerationResult Fail(string error) => new()
    {
        Success = false,
        ErrorMessage = error
    };
}
