// =============================================================================
// MockQuickTapEventPort — Auto-generated Mock adapter for IQuickTapEventPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockQuickTapEventPort : IQuickTapEventPort
{
    /// <summary>Mock implementation of IQuickTapEventPort.ReportEventAsync</summary>
    public Task ReportEventAsync(QuickTapEvent tapEvent, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.CompletedTask;
    }

    /// <summary>Mock implementation of IQuickTapEventPort.GetRecentEventsAsync</summary>
    public Task<IReadOnlyList<QuickTapEvent>> GetRecentEventsAsync(string userId, int maxResults, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<QuickTapEvent>>(default!);
    }

}
