// =============================================================================
// MockPhraseMatchingEngine — Auto-generated Mock adapter for IPhraseMatchingEngine
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockPhraseMatchingEngine : IPhraseMatchingEngine
{
    /// <summary>Mock implementation of IPhraseMatchingEngine.Evaluate</summary>
    public PhraseMatchResult Evaluate(string transcribedText, IReadOnlyList<EmergencyPhrase> activePhrases)
    {
        // TODO: Implement Mock-specific logic
        return default!;
    }

    /// <summary>Mock implementation of IPhraseMatchingEngine.EvaluateSingle</summary>
    public PhraseMatchResult EvaluateSingle(string transcribedText, EmergencyPhrase phrase)
    {
        // TODO: Implement Mock-specific logic
        return default!;
    }

}
