// =============================================================================
// MockEgressComputationPort — Auto-generated Mock adapter for IEgressComputationPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockEgressComputationPort : IEgressComputationPort
{
    /// <summary>Mock implementation of IEgressComputationPort.ComputeEgressRouteAsync</summary>
    public Task<IReadOnlyList<EgressPath>> ComputeEgressRouteAsync(string structureId, string fromRoomId, EgressAccessibility? personCapabilities, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<EgressPath>>(default!);
    }

    /// <summary>Mock implementation of IEgressComputationPort.ComputeAdversarialRouteAsync</summary>
    public Task<IReadOnlyList<EgressPath>> ComputeAdversarialRouteAsync(string structureId, string fromRoomId, AdversarialAStarParams parameters, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<EgressPath>>(default!);
    }

    /// <summary>Mock implementation of IEgressComputationPort.ScoreHideLocationAsync</summary>
    public Task<HideScoreResult> ScoreHideLocationAsync(string roomId, IReadOnlyList<ThreatLocation> threatLocations, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<HideScoreResult>(default!);
    }

    /// <summary>Mock implementation of IEgressComputationPort.DecideRunHideFightAsync</summary>
    public Task<RunHideFightDecision> DecideRunHideFightAsync(string structureId, string personRoomId, IReadOnlyList<ThreatLocation> threatLocations, EgressAccessibility? personCapabilities, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<RunHideFightDecision>(default!);
    }

    /// <summary>Mock implementation of IEgressComputationPort.ComputeGroupEvacuationAsync</summary>
    public Task<GroupEvacuationPlan> ComputeGroupEvacuationAsync(string structureId, IReadOnlyList<string> participantRoomIds, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<GroupEvacuationPlan>(default!);
    }

    /// <summary>Mock implementation of IEgressComputationPort.PruneHazardEdgesAsync</summary>
    public Task<int> PruneHazardEdgesAsync(string structureId, IReadOnlyList<ThreatLocation> hazardLocations, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<int>(default!);
    }

    /// <summary>Mock implementation of IEgressComputationPort.RestoreEdgesAsync</summary>
    public Task<int> RestoreEdgesAsync(string structureId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<int>(default!);
    }

    /// <summary>Mock implementation of IEgressComputationPort.GetSafeHarborsAsync</summary>
    public Task<IReadOnlyList<Room>> GetSafeHarborsAsync(string structureId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<Room>>(default!);
    }

    /// <summary>Mock implementation of IEgressComputationPort.GetEgressPathsAsync</summary>
    public Task<IReadOnlyList<EgressPath>> GetEgressPathsAsync(string structureId, int? floorLevel, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<EgressPath>>(default!);
    }

}
