// =============================================================================
// MockVectorSearchPort — Auto-generated Mock adapter for IVectorSearchPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockVectorSearchPort : IVectorSearchPort
{
    /// <summary>Which vector store backend this adapter uses.</summary>
    public VectorStoreProvider StoreProvider => VectorStoreProvider.Mock;

    /// <summary>Mock implementation of IVectorSearchPort.UpsertAsync</summary>
    public Task<StorageResult<bool>> UpsertAsync(VectorDocument document, CancellationToken ct = default)
    {
        return Task.FromResult(StorageResult<bool>.Ok(true));
    }

    /// <summary>Mock implementation of IVectorSearchPort.UpsertBatchAsync</summary>
    public Task<StorageResult<int>> UpsertBatchAsync(IEnumerable<VectorDocument> documents, CancellationToken ct = default)
    {
        return Task.FromResult(StorageResult<int>.Ok(documents.Count()));
    }

    /// <summary>Mock implementation of IVectorSearchPort.SearchAsync</summary>
    public Task<StorageResult<List<VectorSearchResult>>> SearchAsync(VectorSearchQuery query, CancellationToken ct = default)
    {
        return Task.FromResult(StorageResult<List<VectorSearchResult>>.Ok(new List<VectorSearchResult>()));
    }

    /// <summary>Mock implementation of IVectorSearchPort.DeleteAsync</summary>
    public Task<StorageResult<bool>> DeleteAsync(string documentId, CancellationToken ct = default)
    {
        return Task.FromResult(StorageResult<bool>.Ok(true));
    }

    /// <summary>Mock implementation of IVectorSearchPort.DeleteNamespaceAsync</summary>
    public Task<StorageResult<int>> DeleteNamespaceAsync(string ns, CancellationToken ct = default)
    {
        return Task.FromResult(StorageResult<int>.Ok(0));
    }

    /// <summary>Mock implementation of IVectorSearchPort.CountAsync</summary>
    public Task<long> CountAsync(string? ns = null, CancellationToken ct = default)
    {
        return Task.FromResult(0L);
    }
}
