// =============================================================================
// MockThreatTrackingPort — Auto-generated Mock adapter for IThreatTrackingPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockThreatTrackingPort : IThreatTrackingPort
{
    /// <summary>Mock implementation of IThreatTrackingPort.ReportThreatAsync</summary>
    public Task<ThreatSource> ReportThreatAsync(ThreatSource source, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<ThreatSource>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.UpdateThreatPositionAsync</summary>
    public Task<ThreatSource> UpdateThreatPositionAsync(string threatId, ThreatPosition position, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<ThreatSource>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.GetActiveThreatAsync</summary>
    public Task<ThreatSource?> GetActiveThreatAsync(string threatId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<ThreatSource?>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.GetActiveThreatsInAreaAsync</summary>
    public Task<IReadOnlyList<ThreatSource>> GetActiveThreatsInAreaAsync(double latitude, double longitude, double radiusMeters, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<ThreatSource>>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.RecordThreatEventAsync</summary>
    public Task<ThreatEvent> RecordThreatEventAsync(ThreatEvent threatEvent, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<ThreatEvent>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.GetThreatHistoryAsync</summary>
    public Task<ThreatHistory?> GetThreatHistoryAsync(string threatId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<ThreatHistory?>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.AssessLethalityAsync</summary>
    public Task<int> AssessLethalityAsync(string threatId, LAPAnswer[] answers, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<int>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.ComputeBlockedEgressAsync</summary>
    public Task<IReadOnlyList<BlockedEgressEdge>> ComputeBlockedEgressAsync(string threatId, string structureId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<BlockedEgressEdge>>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.GetSafeHarborsAsync</summary>
    public Task<IReadOnlyList<SafeHarbor>> GetSafeHarborsAsync(double latitude, double longitude, double radiusMeters, bool excludeKnownToThreat, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<SafeHarbor>>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.ClassifyAcousticEventAsync</summary>
    public Task<AcousticEvent> ClassifyAcousticEventAsync(AcousticEvent acousticEvent, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<AcousticEvent>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.ProcessDoorSensorAsync</summary>
    public Task<ThreatSource?> ProcessDoorSensorAsync(DoorSensorReading reading, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<ThreatSource?>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.ProcessGlassBreakAsync</summary>
    public Task<ThreatSource?> ProcessGlassBreakAsync(GlassBreakReading reading, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<ThreatSource?>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.EnableStealthModeAsync</summary>
    public Task<bool> EnableStealthModeAsync(string userId, StealthModeConfig config, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.DisableStealthModeAsync</summary>
    public Task<bool> DisableStealthModeAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IThreatTrackingPort.GetChildrenInHidingAsync</summary>
    public Task<IReadOnlyList<string>> GetChildrenInHidingAsync(string structureId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<string>>(default!);
    }

}
