// =============================================================================
// MockTelephonyPort — Auto-generated Mock adapter for ITelephonyPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockTelephonyPort : ITelephonyPort
{
    /// <summary>Mock implementation of ITelephonyPort.RegisterDeviceAsync</summary>
    public Task<TelephonyDeviceRegistration> RegisterDeviceAsync(TelephonyDeviceRegistration registration, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<TelephonyDeviceRegistration>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.UnregisterDeviceAsync</summary>
    public Task<bool> UnregisterDeviceAsync(string deviceId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.GetDevicesAsync</summary>
    public Task<IReadOnlyList<TelephonyDeviceRegistration>> GetDevicesAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<TelephonyDeviceRegistration>>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.UpdateDeviceAsync</summary>
    public Task<TelephonyDeviceRegistration> UpdateDeviceAsync(TelephonyDeviceRegistration registration, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<TelephonyDeviceRegistration>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.PingDeviceAsync</summary>
    public Task<bool> PingDeviceAsync(string deviceId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.ProcessDtmfEventAsync</summary>
    public Task<bool> ProcessDtmfEventAsync(DtmfEvent dtmfEvent, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.ConfigureDtmfCodeAsync</summary>
    public Task<bool> ConfigureDtmfCodeAsync(string deviceId, string dtmfCode, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.InitiateCallAsync</summary>
    public Task<VoiceCallResult> InitiateCallAsync(VoiceCallRequest request, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<VoiceCallResult>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.CancelCallAsync</summary>
    public Task<bool> CancelCallAsync(string callId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.GetCallResultAsync</summary>
    public Task<VoiceCallResult?> GetCallResultAsync(string callId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<VoiceCallResult?>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.ScheduleCheckInCallAsync</summary>
    public Task<string> ScheduleCheckInCallAsync(string userId, string phoneNumber, string ttsMessage, TimeOnly callTime, DayOfWeek[]? days, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<string>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.CancelScheduledCheckInAsync</summary>
    public Task<bool> CancelScheduledCheckInAsync(string scheduleId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.RecordConsentAsync</summary>
    public Task<TelephonyPrivacyConsent> RecordConsentAsync(TelephonyPrivacyConsent consent, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<TelephonyPrivacyConsent>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.RevokeConsentAsync</summary>
    public Task<bool> RevokeConsentAsync(string userId, string deviceId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of ITelephonyPort.GetConsentAsync</summary>
    public Task<TelephonyPrivacyConsent?> GetConsentAsync(string userId, string deviceId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<TelephonyPrivacyConsent?>(default!);
    }

}
