// =============================================================================
// MockSurveyPort — Auto-generated Mock adapter for ISurveyPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockSurveyPort : ISurveyPort
{
    /// <summary>Mock implementation of ISurveyPort.CreateTemplateAsync</summary>
    public Task<StorageResult<SurveyTemplate>> CreateTemplateAsync(SurveyTemplate template, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<SurveyTemplate>>(default!);
    }

    /// <summary>Mock implementation of ISurveyPort.GetTemplatesByPhaseAsync</summary>
    public Task<StorageResult<List<SurveyTemplate>>> GetTemplatesByPhaseAsync(SubmissionPhase phase, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<SurveyTemplate>>>(default!);
    }

    /// <summary>Mock implementation of ISurveyPort.GetTemplateByIdAsync</summary>
    public Task<StorageResult<SurveyTemplate>> GetTemplateByIdAsync(string templateId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<SurveyTemplate>>(default!);
    }

    /// <summary>Mock implementation of ISurveyPort.SubmitResponseAsync</summary>
    public Task<StorageResult<SurveyResponse>> SubmitResponseAsync(SurveyResponse response, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<SurveyResponse>>(default!);
    }

    /// <summary>Mock implementation of ISurveyPort.GetResponsesByRequestIdAsync</summary>
    public Task<StorageResult<List<SurveyResponse>>> GetResponsesByRequestIdAsync(string requestId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<SurveyResponse>>>(default!);
    }

    /// <summary>Mock implementation of ISurveyPort.GetResponsesByUserIdAsync</summary>
    public Task<StorageResult<List<SurveyResponse>>> GetResponsesByUserIdAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<SurveyResponse>>>(default!);
    }

    /// <summary>Mock implementation of ISurveyPort.GetPendingSurveyUserIdsAsync</summary>
    public Task<StorageResult<List<string>>> GetPendingSurveyUserIdsAsync(string templateId, string requestId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<string>>>(default!);
    }

}
