// =============================================================================
// MockAlarmSystemPort — Auto-generated Mock adapter for IAlarmSystemPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockAlarmSystemPort : IAlarmSystemPort
{
    /// <summary>Mock implementation of IAlarmSystemPort.RegisterPanelAsync</summary>
    public Task<AlarmPanelRegistration> RegisterPanelAsync(AlarmPanelRegistration registration, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<AlarmPanelRegistration>(default!);
    }

    /// <summary>Mock implementation of IAlarmSystemPort.UnregisterPanelAsync</summary>
    public Task<bool> UnregisterPanelAsync(string panelId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IAlarmSystemPort.GetPanelsAsync</summary>
    public Task<IReadOnlyList<AlarmPanelRegistration>> GetPanelsAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<AlarmPanelRegistration>>(default!);
    }

    /// <summary>Mock implementation of IAlarmSystemPort.UpdatePanelAsync</summary>
    public Task<AlarmPanelRegistration> UpdatePanelAsync(AlarmPanelRegistration registration, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<AlarmPanelRegistration>(default!);
    }

    /// <summary>Mock implementation of IAlarmSystemPort.ProcessEventAsync</summary>
    public Task<IoTAlertResult> ProcessEventAsync(AlarmEvent alarmEvent, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IoTAlertResult>(default!);
    }

    /// <summary>Mock implementation of IAlarmSystemPort.ProcessContactIdAsync</summary>
    public Task<IoTAlertResult> ProcessContactIdAsync(string rawContactIdPacket, string sourceIpOrPhone, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IoTAlertResult>(default!);
    }

    /// <summary>Mock implementation of IAlarmSystemPort.ProcessSiaDc07Async</summary>
    public Task<IoTAlertResult> ProcessSiaDc07Async(byte[] encryptedPacket, string sourceIp, int sourcePort, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IoTAlertResult>(default!);
    }

    /// <summary>Mock implementation of IAlarmSystemPort.GetRecentEventsAsync</summary>
    public Task<IReadOnlyList<AlarmEvent>> GetRecentEventsAsync(string userId, int maxResults, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<AlarmEvent>>(default!);
    }

    /// <summary>Mock implementation of IAlarmSystemPort.UpdateZoneMapAsync</summary>
    public Task<bool> UpdateZoneMapAsync(string panelId, IReadOnlyDictionary<int, AlarmZoneInfo> zoneMap, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IAlarmSystemPort.DiscoverZonesAsync</summary>
    public Task<IReadOnlyDictionary<int, AlarmZoneInfo>?> DiscoverZonesAsync(string panelId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyDictionary<int, AlarmZoneInfo>?>(default!);
    }

    /// <summary>Mock implementation of IAlarmSystemPort.LinkPlatformAccountAsync</summary>
    public Task<bool> LinkPlatformAccountAsync(string userId, AlarmPlatform platform, string? oauthCode, string? apiKey, string? redirectUri, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IAlarmSystemPort.UnlinkPlatformAccountAsync</summary>
    public Task<bool> UnlinkPlatformAccountAsync(string userId, AlarmPlatform platform, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IAlarmSystemPort.GetPanelStatusAsync</summary>
    public Task<AlarmPanelStatus?> GetPanelStatusAsync(string panelId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<AlarmPanelStatus?>(default!);
    }

}
