// =============================================================================
// MockDevWorkPort — Auto-generated Mock adapter for IDevWorkPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockDevWorkPort : IDevWorkPort
{
    /// <summary>Mock implementation of IDevWorkPort.LogWorkAsync</summary>
    public Task<StorageResult<DevWorkLog>> LogWorkAsync(DevWorkLog log, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<DevWorkLog>>(default!);
    }

    /// <summary>Mock implementation of IDevWorkPort.GetByIdAsync</summary>
    public Task<StorageResult<DevWorkLog>> GetByIdAsync(string logId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<DevWorkLog>>(default!);
    }

    /// <summary>Mock implementation of IDevWorkPort.GetRecentLogsAsync</summary>
    public Task<StorageResult<List<DevWorkLog>>> GetRecentLogsAsync(int limit, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<DevWorkLog>>>(default!);
    }

    /// <summary>Mock implementation of IDevWorkPort.GetBySessionIdAsync</summary>
    public Task<StorageResult<List<DevWorkLog>>> GetBySessionIdAsync(string sessionId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<DevWorkLog>>>(default!);
    }

    /// <summary>Mock implementation of IDevWorkPort.GetByFeatureIdAsync</summary>
    public Task<StorageResult<List<DevWorkLog>>> GetByFeatureIdAsync(string featureId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<DevWorkLog>>>(default!);
    }

    /// <summary>Mock implementation of IDevWorkPort.UpdateStatusAsync</summary>
    public Task<StorageResult<bool>> UpdateStatusAsync(string logId, string status, string? errorMessage, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<bool>>(default!);
    }

}
