// =============================================================================
// MockBlobStoragePort — Auto-generated Mock adapter for IBlobStoragePort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockBlobStoragePort : IBlobStoragePort
{
    /// <summary>Mock implementation of IBlobStoragePort.UploadAsync</summary>
    public Task<StorageResult<string>> UploadAsync(string container, string blobName, Stream content, string mimeType, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<string>>(default!);
    }

    /// <summary>Mock implementation of IBlobStoragePort.DownloadAsync</summary>
    public Task<StorageResult<Stream>> DownloadAsync(string container, string blobName, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<Stream>>(default!);
    }

    /// <summary>Mock implementation of IBlobStoragePort.DeleteAsync</summary>
    public Task<StorageResult<bool>> DeleteAsync(string container, string blobName, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<bool>>(default!);
    }

    /// <summary>Mock implementation of IBlobStoragePort.GetDownloadUrlAsync</summary>
    public Task<string> GetDownloadUrlAsync(string container, string blobName, TimeSpan expiry, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<string>(default!);
    }

    /// <summary>Mock implementation of IBlobStoragePort.ExistsAsync</summary>
    public Task<bool> ExistsAsync(string container, string blobName, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

}
