// =============================================================================
// MockEmergencyServicesPort — Auto-generated Mock adapter for IEmergencyServicesPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockEmergencyServicesPort : IEmergencyServicesPort
{
    /// <summary>Mock implementation of IEmergencyServicesPort.Initiate911CallAsync</summary>
    public Task<Emergency911Result> Initiate911CallAsync(Emergency911Request request, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<Emergency911Result>(default!);
    }

    /// <summary>Mock implementation of IEmergencyServicesPort.Cancel911CallAsync</summary>
    public Task<bool> Cancel911CallAsync(string requestId, string cancelledBy, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IEmergencyServicesPort.Confirm911CallAsync</summary>
    public Task<Emergency911Result> Confirm911CallAsync(string requestId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<Emergency911Result>(default!);
    }

    /// <summary>Mock implementation of IEmergencyServicesPort.Get911CallResultAsync</summary>
    public Task<Emergency911Result?> Get911CallResultAsync(string requestId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<Emergency911Result?>(default!);
    }

    /// <summary>Mock implementation of IEmergencyServicesPort.PushLocationToRapidSosAsync</summary>
    public Task<bool> PushLocationToRapidSosAsync(RapidSosLocationPush locationData, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IEmergencyServicesPort.UpdateRapidSosLocationAsync</summary>
    public Task<bool> UpdateRapidSosLocationAsync(string requestId, double latitude, double longitude, double? accuracyMeters, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IEmergencyServicesPort.CloseRapidSosSessionAsync</summary>
    public Task<bool> CloseRapidSosSessionAsync(string requestId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IEmergencyServicesPort.RegisterE911AddressAsync</summary>
    public Task<bool> RegisterE911AddressAsync(string userId, string address, string city, string state, string zip, string country, string callbackNumber, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IEmergencyServicesPort.HasRegisteredE911AddressAsync</summary>
    public Task<bool> HasRegisteredE911AddressAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IEmergencyServicesPort.GetConsentAsync</summary>
    public Task<Emergency911Consent?> GetConsentAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<Emergency911Consent?>(default!);
    }

    /// <summary>Mock implementation of IEmergencyServicesPort.UpdateConsentAsync</summary>
    public Task<Emergency911Consent> UpdateConsentAsync(Emergency911Consent consent, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<Emergency911Consent>(default!);
    }

    /// <summary>Mock implementation of IEmergencyServicesPort.GetCallHistoryAsync</summary>
    public Task<IReadOnlyList<Emergency911Result>> GetCallHistoryAsync(string userId, int maxResults, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<Emergency911Result>>(default!);
    }

}
