// =============================================================================
// MockStorageService — Auto-generated Mock adapter for IStorageService
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using System.Collections.Concurrent;
using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockStorageService : IStorageService
{
    private readonly ConcurrentDictionary<string, ConcurrentDictionary<string, object>> _store = new();
    private readonly ConcurrentBag<OfflineQueueEntry> _offlineQueue = new();

    private ConcurrentDictionary<string, object> GetCollection(string collection)
        => _store.GetOrAdd(collection, _ => new ConcurrentDictionary<string, object>());

    /// <summary>Mock implementation of IStorageService.StoreAsync</summary>
    public Task<StorageResult<T>> StoreAsync<T>(string collection, string id, T entity, CancellationToken ct = default) where T : class
    {
        GetCollection(collection)[id] = entity!;
        return Task.FromResult(StorageResult<T>.Ok(entity));
    }

    /// <summary>Mock implementation of IStorageService.RetrieveAsync</summary>
    public Task<StorageResult<T>> RetrieveAsync<T>(string collection, string id, CancellationToken ct = default) where T : class
    {
        if (GetCollection(collection).TryGetValue(id, out var value) && value is T typed)
            return Task.FromResult(StorageResult<T>.Ok(typed));
        return Task.FromResult(StorageResult<T>.Fail($"Not found: {collection}/{id}"));
    }

    /// <summary>Mock implementation of IStorageService.QueryAsync</summary>
    public Task<StorageResult<List<T>>> QueryAsync<T>(string collection, Func<T, bool>? predicate = null, CancellationToken ct = default) where T : class
    {
        var items = GetCollection(collection).Values.OfType<T>();
        if (predicate != null)
            items = items.Where(predicate);
        return Task.FromResult(StorageResult<List<T>>.Ok(items.ToList()));
    }

    /// <summary>Mock implementation of IStorageService.DeleteAsync</summary>
    public Task<StorageResult<bool>> DeleteAsync(string collection, string id, CancellationToken ct = default)
    {
        var removed = GetCollection(collection).TryRemove(id, out _);
        return Task.FromResult(StorageResult<bool>.Ok(removed));
    }

    /// <summary>Mock implementation of IStorageService.ExistsAsync</summary>
    public Task<bool> ExistsAsync(string collection, string id, CancellationToken ct = default)
    {
        return Task.FromResult(GetCollection(collection).ContainsKey(id));
    }

    /// <summary>Mock implementation of IStorageService.CountAsync</summary>
    public Task<long> CountAsync(string collection, CancellationToken ct = default)
    {
        return Task.FromResult((long)GetCollection(collection).Count);
    }

    /// <summary>Mock implementation of IStorageService.EnqueueOfflineAsync</summary>
    public Task EnqueueOfflineAsync(OfflineQueueEntry entry, CancellationToken ct = default)
    {
        _offlineQueue.Add(entry);
        return Task.CompletedTask;
    }

    /// <summary>Mock implementation of IStorageService.GetPendingQueueAsync</summary>
    public Task<List<OfflineQueueEntry>> GetPendingQueueAsync(CancellationToken ct = default)
    {
        return Task.FromResult(_offlineQueue.ToList());
    }

    /// <summary>Mock implementation of IStorageService.MarkSyncedAsync</summary>
    public Task MarkSyncedAsync(string entryId, CancellationToken ct = default)
    {
        // In-memory mock — no-op for mark synced
        return Task.CompletedTask;
    }
}
