// =============================================================================
// MockFeatureTrackingPort — Auto-generated Mock adapter for IFeatureTrackingPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockFeatureTrackingPort : IFeatureTrackingPort
{
    /// <summary>Mock implementation of IFeatureTrackingPort.GetAllAsync</summary>
    public Task<StorageResult<List<FeatureImplementation>>> GetAllAsync(CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<FeatureImplementation>>>(default!);
    }

    /// <summary>Mock implementation of IFeatureTrackingPort.GetByIdAsync</summary>
    public Task<StorageResult<FeatureImplementation>> GetByIdAsync(string featureId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<FeatureImplementation>>(default!);
    }

    /// <summary>Mock implementation of IFeatureTrackingPort.GetByCategoryAsync</summary>
    public Task<StorageResult<List<FeatureImplementation>>> GetByCategoryAsync(FeatureCategory category, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<FeatureImplementation>>>(default!);
    }

    /// <summary>Mock implementation of IFeatureTrackingPort.GetByStatusAsync</summary>
    public Task<StorageResult<List<FeatureImplementation>>> GetByStatusAsync(FeatureStatus status, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<FeatureImplementation>>>(default!);
    }

    /// <summary>Mock implementation of IFeatureTrackingPort.UpsertAsync</summary>
    public Task<StorageResult<FeatureImplementation>> UpsertAsync(FeatureImplementation feature, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<FeatureImplementation>>(default!);
    }

    /// <summary>Mock implementation of IFeatureTrackingPort.UpdateStatusAsync</summary>
    public Task<StorageResult<bool>> UpdateStatusAsync(string featureId, FeatureStatus status, int progressPercent, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<bool>>(default!);
    }

    /// <summary>Mock implementation of IFeatureTrackingPort.DeleteAsync</summary>
    public Task<StorageResult<bool>> DeleteAsync(string featureId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<bool>>(default!);
    }

    /// <summary>Mock implementation of IFeatureTrackingPort.GetCategoryCountsAsync</summary>
    public Task<StorageResult<Dictionary<FeatureCategory, int>>> GetCategoryCountsAsync(CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<Dictionary<FeatureCategory, int>>>(default!);
    }

    /// <summary>Mock implementation of IFeatureTrackingPort.GetStatusCountsAsync</summary>
    public Task<StorageResult<Dictionary<FeatureStatus, int>>> GetStatusCountsAsync(CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<Dictionary<FeatureStatus, int>>>(default!);
    }

}
