// =============================================================================
// MockSpatialIndex — Auto-generated Mock adapter for ISpatialIndex
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockSpatialIndex : ISpatialIndex
{
    /// <summary>Mock implementation of ISpatialIndex.IndexAsync</summary>
    public Task IndexAsync(string entityId, string entityType, double latitude, double longitude, Dictionary<string, string>? metadata, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.CompletedTask;
    }

    /// <summary>Mock implementation of ISpatialIndex.RemoveAsync</summary>
    public Task RemoveAsync(string entityId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.CompletedTask;
    }

    /// <summary>Mock implementation of ISpatialIndex.FindNearbyAsync</summary>
    public Task<List<SpatialResult>> FindNearbyAsync(SpatialQuery query, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<List<SpatialResult>>(default!);
    }

    /// <summary>Mock implementation of ISpatialIndex.GetRingAsync</summary>
    public Task<List<SpatialResult>> GetRingAsync(int ringLevel, double centerLat, double centerLng, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<List<SpatialResult>>(default!);
    }

    /// <summary>Mock implementation of ISpatialIndex.UpdatePositionAsync</summary>
    public Task UpdatePositionAsync(string entityId, double latitude, double longitude, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.CompletedTask;
    }

}
