// =============================================================================
// MockPersonCapabilityPort — Auto-generated Mock adapter for IPersonCapabilityPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockPersonCapabilityPort : IPersonCapabilityPort
{
    /// <summary>Mock implementation of IPersonCapabilityPort.GetProfileAsync</summary>
    public Task<PersonCapabilityProfile?> GetProfileAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<PersonCapabilityProfile?>(default!);
    }

    /// <summary>Mock implementation of IPersonCapabilityPort.UpdateProfileAsync</summary>
    public Task<PersonCapabilityProfile> UpdateProfileAsync(PersonCapabilityProfile profile, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<PersonCapabilityProfile>(default!);
    }

    /// <summary>Mock implementation of IPersonCapabilityPort.GetCMISTProfileAsync</summary>
    public Task<CMISTProfile?> GetCMISTProfileAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<CMISTProfile?>(default!);
    }

    /// <summary>Mock implementation of IPersonCapabilityPort.UpdateCMISTProfileAsync</summary>
    public Task<CMISTProfile> UpdateCMISTProfileAsync(CMISTProfile profile, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<CMISTProfile>(default!);
    }

    /// <summary>Mock implementation of IPersonCapabilityPort.ComputeAccessibleEgressWeightsAsync</summary>
    public Task<IReadOnlyList<AccessibleEgressWeight>> ComputeAccessibleEgressWeightsAsync(string userId, string structureId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<AccessibleEgressWeight>>(default!);
    }

    /// <summary>Mock implementation of IPersonCapabilityPort.ComputeOccupantLoadAsync</summary>
    public Task<OccupantLoadCalculation> ComputeOccupantLoadAsync(string roomId, string roomType, double areaSqFt, string occupancyGroup, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<OccupantLoadCalculation>(default!);
    }

    /// <summary>Mock implementation of IPersonCapabilityPort.GetOccupantsWithSpecialNeedsAsync</summary>
    public Task<IReadOnlyList<PersonCapabilityProfile>> GetOccupantsWithSpecialNeedsAsync(string structureId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<PersonCapabilityProfile>>(default!);
    }

    /// <summary>Mock implementation of IPersonCapabilityPort.GetEvacuationPriorityAsync</summary>
    public Task<int> GetEvacuationPriorityAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<int>(default!);
    }

    /// <summary>Mock implementation of IPersonCapabilityPort.RequiresCaretakerAsync</summary>
    public Task<bool> RequiresCaretakerAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IPersonCapabilityPort.GetLanguagesInStructureAsync</summary>
    public Task<IReadOnlyList<string>> GetLanguagesInStructureAsync(string structureId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<string>>(default!);
    }

}
