// =============================================================================
// MockEmbeddingPort — Auto-generated Mock adapter for IEmbeddingPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockEmbeddingPort : IEmbeddingPort
{
    private static readonly Random _rng = new();

    /// <summary>Which provider this adapter uses.</summary>
    public EmbeddingProvider Provider => EmbeddingProvider.Mock;

    /// <summary>Dimensionality of the embeddings produced.</summary>
    public int Dimensions => 1536;

    /// <summary>Mock implementation of IEmbeddingPort.EmbedAsync — returns random unit vector.</summary>
    public Task<StorageResult<float[]>> EmbedAsync(string text, CancellationToken ct = default)
    {
        var vector = GenerateRandomUnitVector(Dimensions);
        return Task.FromResult(StorageResult<float[]>.Ok(vector));
    }

    /// <summary>Mock implementation of IEmbeddingPort.EmbedBatchAsync</summary>
    public Task<StorageResult<float[][]>> EmbedBatchAsync(string[] texts, CancellationToken ct = default)
    {
        var batch = new float[texts.Length][];
        for (int i = 0; i < texts.Length; i++)
            batch[i] = GenerateRandomUnitVector(Dimensions);
        return Task.FromResult(StorageResult<float[][]>.Ok(batch));
    }

    /// <summary>Mock implementation of IEmbeddingPort.EmbedDocumentAsync</summary>
    public Task<StorageResult<VectorDocument>> EmbedDocumentAsync(string content, string source, string ns, List<string>? tags = null, CancellationToken ct = default)
    {
        var doc = new VectorDocument
        {
            Id = Guid.NewGuid().ToString(),
            Content = content,
            Source = source,
            Namespace = ns,
            Tags = tags ?? new List<string>(),
            Embedding = GenerateRandomUnitVector(Dimensions),
            Provider = Provider,
            CreatedAt = DateTime.UtcNow
        };
        return Task.FromResult(StorageResult<VectorDocument>.Ok(doc));
    }

    private static float[] GenerateRandomUnitVector(int dims)
    {
        var v = new float[dims];
        double sum = 0;
        for (int i = 0; i < dims; i++)
        {
            v[i] = (float)(_rng.NextDouble() * 2 - 1);
            sum += v[i] * v[i];
        }
        var mag = (float)Math.Sqrt(sum);
        for (int i = 0; i < dims; i++)
            v[i] /= mag;
        return v;
    }
}
