// =============================================================================
// MockAuthPort — Auto-generated Mock adapter for IAuthPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockAuthPort : IAuthPort
{
    /// <summary>Which auth provider this adapter uses.</summary>
    public string ProviderName => "Mock";

    /// <summary>Mock implementation of IAuthPort.ValidateTokenAsync</summary>
    public Task<StorageResult<WatchUserClaims>> ValidateTokenAsync(string idToken, CancellationToken ct = default)
    {
        var claims = new WatchUserClaims
        {
            Uid = "mock-uid-001",
            Email = "mock@thewatch.dev",
            DisplayName = "Mock User",
            Provider = "mock",
            Roles = new List<string> { "user" },
            TokenIssuedAt = DateTime.UtcNow,
            TokenExpiresAt = DateTime.UtcNow.AddHours(1)
        };
        return Task.FromResult(StorageResult<WatchUserClaims>.Ok(claims));
    }

    /// <summary>Mock implementation of IAuthPort.RevokeTokensAsync</summary>
    public Task<bool> RevokeTokensAsync(string uid, CancellationToken ct = default)
    {
        return Task.FromResult(true);
    }

    /// <summary>Mock implementation of IAuthPort.SetCustomClaimsAsync</summary>
    public Task<bool> SetCustomClaimsAsync(string uid, Dictionary<string, object> claims, CancellationToken ct = default)
    {
        return Task.FromResult(true);
    }
}
