// =============================================================================
// MockBuildOutputPort — Auto-generated Mock adapter for IBuildOutputPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockBuildOutputPort : IBuildOutputPort
{
    /// <summary>Which store this adapter persists to.</summary>
    public BuildOutputStore Store => BuildOutputStore.Mock;

    /// <summary>Mock implementation of IBuildOutputPort.SaveAsync</summary>
    public Task<StorageResult<BuildOutput>> SaveAsync(BuildOutput output, CancellationToken ct = default)
    {
        return Task.FromResult(StorageResult<BuildOutput>.Ok(output));
    }

    /// <summary>Mock implementation of IBuildOutputPort.GetByIdAsync</summary>
    public Task<StorageResult<BuildOutput>> GetByIdAsync(string buildId, CancellationToken ct = default)
    {
        return Task.FromResult(StorageResult<BuildOutput>.Ok(default!));
    }

    /// <summary>Mock implementation of IBuildOutputPort.GetRecentAsync</summary>
    public Task<StorageResult<List<BuildOutput>>> GetRecentAsync(int limit = 50, string? projectName = null, CancellationToken ct = default)
    {
        return Task.FromResult(StorageResult<List<BuildOutput>>.Ok(new List<BuildOutput>()));
    }

    /// <summary>Mock implementation of IBuildOutputPort.GetFailedAsync</summary>
    public Task<StorageResult<List<BuildOutput>>> GetFailedAsync(DateTime since, string? projectName = null, CancellationToken ct = default)
    {
        return Task.FromResult(StorageResult<List<BuildOutput>>.Ok(new List<BuildOutput>()));
    }

    /// <summary>Mock implementation of IBuildOutputPort.GetDiagnosticsAsync</summary>
    public Task<StorageResult<List<BuildDiagnostic>>> GetDiagnosticsAsync(DateTime since, BuildOutputSeverity? severity = null, string? projectName = null, CancellationToken ct = default)
    {
        return Task.FromResult(StorageResult<List<BuildDiagnostic>>.Ok(new List<BuildDiagnostic>()));
    }

    /// <summary>Mock implementation of IBuildOutputPort.GetStatsAsync</summary>
    public Task<StorageResult<BuildOutputStats>> GetStatsAsync(DateTime since, CancellationToken ct = default)
    {
        return Task.FromResult(StorageResult<BuildOutputStats>.Ok(new BuildOutputStats()));
    }

    /// <summary>Mock implementation of IBuildOutputPort.PurgeAsync</summary>
    public Task<StorageResult<int>> PurgeAsync(DateTime olderThan, CancellationToken ct = default)
    {
        return Task.FromResult(StorageResult<int>.Ok(0));
    }
}
