// =============================================================================
// MockOraclePort — Auto-generated Mock adapter for IOraclePort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Dtos;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockOraclePort : IOraclePort
{
    /// <summary>Mock implementation of IOraclePort.GetHealthCheckAsync</summary>
    public Task<List<HealthStatusDto>> GetHealthCheckAsync(CancellationToken ct = default)
    {
        return Task.FromResult(new List<HealthStatusDto>
        {
            new("Oracle-Mock", true, "Mock Oracle adapter is healthy", DateTime.UtcNow)
        });
    }

    /// <summary>Mock implementation of IOraclePort.GetAutonomousDatabaseStatusAsync</summary>
    public Task<Dictionary<string, object>> GetAutonomousDatabaseStatusAsync(string databaseId, CancellationToken ct = default)
    {
        return Task.FromResult(new Dictionary<string, object> { ["status"] = "AVAILABLE", ["databaseId"] = databaseId });
    }

    /// <summary>Mock implementation of IOraclePort.ListAutonomousDatabasesAsync</summary>
    public Task<List<Dictionary<string, object>>> ListAutonomousDatabasesAsync(CancellationToken ct = default)
    {
        return Task.FromResult(new List<Dictionary<string, object>>());
    }

    /// <summary>Mock implementation of IOraclePort.ExecuteAutonomousDbQueryAsync</summary>
    public Task<Dictionary<string, object>> ExecuteAutonomousDbQueryAsync(string databaseId, string sql, CancellationToken ct = default)
    {
        return Task.FromResult(new Dictionary<string, object> { ["results"] = Array.Empty<object>() });
    }

    /// <summary>Mock implementation of IOraclePort.ListObjectStorageBucketsAsync</summary>
    public Task<List<Dictionary<string, object>>> ListObjectStorageBucketsAsync(string namespaceName, string compartmentId, CancellationToken ct = default)
    {
        return Task.FromResult(new List<Dictionary<string, object>>());
    }

    /// <summary>Mock implementation of IOraclePort.ListObjectStorageObjectsAsync</summary>
    public Task<List<Dictionary<string, object>>> ListObjectStorageObjectsAsync(string namespaceName, string bucketName, string? prefix = null, CancellationToken ct = default)
    {
        return Task.FromResult(new List<Dictionary<string, object>>());
    }

    /// <summary>Mock implementation of IOraclePort.GetObjectStorageObjectMetadataAsync</summary>
    public Task<Dictionary<string, object>> GetObjectStorageObjectMetadataAsync(string namespaceName, string bucketName, string objectName, CancellationToken ct = default)
    {
        return Task.FromResult(new Dictionary<string, object> { ["name"] = objectName });
    }

    /// <summary>Mock implementation of IOraclePort.ListNotificationTopicsAsync</summary>
    public Task<List<Dictionary<string, object>>> ListNotificationTopicsAsync(string compartmentId, CancellationToken ct = default)
    {
        return Task.FromResult(new List<Dictionary<string, object>>());
    }

    /// <summary>Mock implementation of IOraclePort.PublishNotificationAsync</summary>
    public Task PublishNotificationAsync(string topicId, string title, string body, CancellationToken ct = default)
    {
        return Task.CompletedTask;
    }
}
