// =============================================================================
// MockContextRetrievalPort — Auto-generated Mock adapter for IContextRetrievalPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockContextRetrievalPort : IContextRetrievalPort
{
    /// <summary>Mock implementation of IContextRetrievalPort.RetrieveContextAsync</summary>
    public Task<StorageResult<List<ContextChunk>>> RetrieveContextAsync(string query, string[]? namespaces, int maxTokens, int topK, float minScore, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<ContextChunk>>>(default!);
    }

    /// <summary>Mock implementation of IContextRetrievalPort.IngestAsync</summary>
    public Task<StorageResult<int>> IngestAsync(string content, string source, string ns, List<string>? tags, int chunkSize, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<int>>(default!);
    }

}
