// =============================================================================
// MockAuditTrail — Auto-generated Mock adapter for IAuditTrail
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockAuditTrail : IAuditTrail
{
    /// <summary>Mock implementation of IAuditTrail.AppendAsync</summary>
    public Task AppendAsync(AuditEntry entry, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.CompletedTask;
    }

    /// <summary>Mock implementation of IAuditTrail.AppendBatchAsync</summary>
    public Task AppendBatchAsync(IReadOnlyList<AuditEntry> entries, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.CompletedTask;
    }

    /// <summary>Mock implementation of IAuditTrail.GetTrailAsync</summary>
    public Task<List<AuditEntry>> GetTrailAsync(DateTime from, DateTime to, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<List<AuditEntry>>(default!);
    }

    /// <summary>Mock implementation of IAuditTrail.GetTrailByEntityAsync</summary>
    public Task<List<AuditEntry>> GetTrailByEntityAsync(string entityType, string entityId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<List<AuditEntry>>(default!);
    }

    /// <summary>Mock implementation of IAuditTrail.GetTrailByUserAsync</summary>
    public Task<List<AuditEntry>> GetTrailByUserAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<List<AuditEntry>>(default!);
    }

    /// <summary>Mock implementation of IAuditTrail.GetTrailByCorrelationAsync</summary>
    public Task<List<AuditEntry>> GetTrailByCorrelationAsync(string correlationId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<List<AuditEntry>>(default!);
    }

    /// <summary>Mock implementation of IAuditTrail.GetTrailByActionAsync</summary>
    public Task<List<AuditEntry>> GetTrailByActionAsync(AuditAction action, DateTime? from, DateTime? to, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<List<AuditEntry>>(default!);
    }

    /// <summary>Mock implementation of IAuditTrail.GetTrailBySeverityAsync</summary>
    public Task<List<AuditEntry>> GetTrailBySeverityAsync(AuditSeverity minSeverity, DateTime from, DateTime to, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<List<AuditEntry>>(default!);
    }

    /// <summary>Mock implementation of IAuditTrail.GetTrailBySourceAsync</summary>
    public Task<List<AuditEntry>> GetTrailBySourceAsync(string sourceSystem, string? sourceComponent, DateTime? from, DateTime? to, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<List<AuditEntry>>(default!);
    }

    /// <summary>Mock implementation of IAuditTrail.VerifyIntegrityAsync</summary>
    public Task<bool> VerifyIntegrityAsync(CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IAuditTrail.VerifyIntegrityRangeAsync</summary>
    public Task<bool> VerifyIntegrityRangeAsync(DateTime from, DateTime to, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IAuditTrail.GetLatestEntryAsync</summary>
    public Task<AuditEntry?> GetLatestEntryAsync(CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<AuditEntry?>(default!);
    }

    /// <summary>Mock implementation of IAuditTrail.GetStatisticsAsync</summary>
    public Task<AuditStatistics> GetStatisticsAsync(DateTime from, DateTime to, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<AuditStatistics>(default!);
    }

}
