// =============================================================================
// MockStructurePort — Auto-generated Mock adapter for IStructurePort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockStructurePort : IStructurePort
{
    /// <summary>Mock implementation of IStructurePort.GetBuildingAsync</summary>
    public Task<BuildingData?> GetBuildingAsync(string buildingId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<BuildingData?>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.GetBuildingByAPNAsync</summary>
    public Task<BuildingData?> GetBuildingByAPNAsync(string apn, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<BuildingData?>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.GetBuildingsInAreaAsync</summary>
    public Task<IReadOnlyList<BuildingData>> GetBuildingsInAreaAsync(double lat, double lng, double radiusMeters, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<BuildingData>>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.UpdateBuildingAsync</summary>
    public Task<BuildingData> UpdateBuildingAsync(BuildingData building, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<BuildingData>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.GetRoomsAsync</summary>
    public Task<IReadOnlyList<RoomData>> GetRoomsAsync(string buildingId, int? floorLevel, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<RoomData>>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.GetFireProtectionAsync</summary>
    public Task<FireProtectionSystem?> GetFireProtectionAsync(string buildingId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<FireProtectionSystem?>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.ReportHazardAsync</summary>
    public Task<HazardCondition> ReportHazardAsync(HazardCondition hazard, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<HazardCondition>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.GetActiveHazardsAsync</summary>
    public Task<IReadOnlyList<HazardCondition>> GetActiveHazardsAsync(string buildingId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<HazardCondition>>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.ResolveHazardAsync</summary>
    public Task<HazardCondition> ResolveHazardAsync(string hazardId, string resolution, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<HazardCondition>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.GetWeatherAlertsAsync</summary>
    public Task<IReadOnlyList<WeatherAlert>> GetWeatherAlertsAsync(double lat, double lng, double radiusKm, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<WeatherAlert>>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.LookupHazmatAsync</summary>
    public Task<HazmatInfo?> LookupHazmatAsync(string unNumber, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<HazmatInfo?>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.GetSeismicAlertsAsync</summary>
    public Task<IReadOnlyList<SeismicAlert>> GetSeismicAlertsAsync(double lat, double lng, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<SeismicAlert>>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.ComputeExplosionRiskAsync</summary>
    public Task<(bool IsAtRisk, string FuelType, string Recommendation)> ComputeExplosionRiskAsync(string buildingId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<(bool IsAtRisk, string FuelType, string Recommendation)>(default!);
    }

    /// <summary>Mock implementation of IStructurePort.ComputeFloodVulnerabilityAsync</summary>
    public Task<(bool IsVulnerable, string FoundationType, string Recommendation)> ComputeFloodVulnerabilityAsync(string buildingId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<(bool IsVulnerable, string FoundationType, string Recommendation)>(default!);
    }

}
