// =============================================================================
// MockQuickTapConfigurationPort — Auto-generated Mock adapter for IQuickTapConfigurationPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockQuickTapConfigurationPort : IQuickTapConfigurationPort
{
    /// <summary>Mock implementation of IQuickTapConfigurationPort.GetConfigurationAsync</summary>
    public Task<QuickTapConfiguration> GetConfigurationAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<QuickTapConfiguration>(default!);
    }

    /// <summary>Mock implementation of IQuickTapConfigurationPort.UpdateConfigurationAsync</summary>
    public Task UpdateConfigurationAsync(QuickTapConfiguration config, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.CompletedTask;
    }

}
