// =============================================================================
// MockPhraseDetectionPort — Auto-generated Mock adapter for IPhraseDetectionPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockPhraseDetectionPort : IPhraseDetectionPort
{
    /// <summary>Is the listener currently active and processing audio?</summary>
    public bool IsListening { get; private set; }

    /// <summary>Is on-device speech recognition available on this device?</summary>
    public bool IsAvailable => true;

    /// <summary>
    /// Event raised when speech is transcribed.
    /// </summary>
    public event EventHandler<SpeechTranscriptionEventArgs>? OnSpeechTranscribed;

    /// <summary>
    /// Event raised when a phrase match is detected.
    /// </summary>
    public event EventHandler<PhraseMatchResult>? OnPhraseDetected;

    /// <summary>Mock implementation of IPhraseDetectionPort.StartListeningAsync</summary>
    public Task<bool> StartListeningAsync(CancellationToken ct = default)
    {
        IsListening = true;
        return Task.FromResult(true);
    }

    /// <summary>Mock implementation of IPhraseDetectionPort.StopListeningAsync</summary>
    public Task StopListeningAsync(CancellationToken ct = default)
    {
        IsListening = false;
        return Task.CompletedTask;
    }

    /// <summary>
    /// Simulate a speech transcription event for testing purposes.
    /// Example: mockPort.SimulateTranscription("I need to walk the dog", 0.95f);
    /// </summary>
    public void SimulateTranscription(string text, float confidence = 0.95f)
    {
        OnSpeechTranscribed?.Invoke(this, new SpeechTranscriptionEventArgs
        {
            TranscribedText = text,
            Confidence = confidence,
            IsFinal = true,
            Timestamp = DateTime.UtcNow
        });
    }

    /// <summary>
    /// Simulate a phrase detection event for testing purposes.
    /// </summary>
    public void SimulatePhraseDetection(PhraseMatchResult result)
    {
        OnPhraseDetected?.Invoke(this, result);
    }
}
