// =============================================================================
// MockCloudflarePort — Auto-generated Mock adapter for ICloudflarePort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Dtos;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockCloudflarePort : ICloudflarePort
{
    /// <summary>Mock implementation of ICloudflarePort.GetHealthCheckAsync</summary>
    public Task<List<HealthStatusDto>> GetHealthCheckAsync(CancellationToken ct = default)
    {
        return Task.FromResult(new List<HealthStatusDto>
        {
            new("Cloudflare-Mock", true, "Mock Cloudflare adapter is healthy", DateTime.UtcNow)
        });
    }

    /// <summary>Mock implementation of ICloudflarePort.GetWorkerDeploymentStatusAsync</summary>
    public Task<Dictionary<string, object>> GetWorkerDeploymentStatusAsync(string workerName, CancellationToken ct = default)
    {
        return Task.FromResult(new Dictionary<string, object> { ["status"] = "deployed", ["worker"] = workerName });
    }

    /// <summary>Mock implementation of ICloudflarePort.ListWorkersAsync</summary>
    public Task<List<Dictionary<string, object>>> ListWorkersAsync(CancellationToken ct = default)
    {
        return Task.FromResult(new List<Dictionary<string, object>>());
    }

    /// <summary>Mock implementation of ICloudflarePort.ListR2BucketsAsync</summary>
    public Task<List<Dictionary<string, object>>> ListR2BucketsAsync(CancellationToken ct = default)
    {
        return Task.FromResult(new List<Dictionary<string, object>>());
    }

    /// <summary>Mock implementation of ICloudflarePort.GetR2BucketDetailsAsync</summary>
    public Task<Dictionary<string, object>> GetR2BucketDetailsAsync(string bucketName, CancellationToken ct = default)
    {
        return Task.FromResult(new Dictionary<string, object> { ["name"] = bucketName });
    }

    /// <summary>Mock implementation of ICloudflarePort.ListR2ObjectsAsync</summary>
    public Task<List<Dictionary<string, object>>> ListR2ObjectsAsync(string bucketName, string? prefix = null, CancellationToken ct = default)
    {
        return Task.FromResult(new List<Dictionary<string, object>>());
    }

    /// <summary>Mock implementation of ICloudflarePort.ListD1DatabasesAsync</summary>
    public Task<List<Dictionary<string, object>>> ListD1DatabasesAsync(CancellationToken ct = default)
    {
        return Task.FromResult(new List<Dictionary<string, object>>());
    }

    /// <summary>Mock implementation of ICloudflarePort.QueryD1Async</summary>
    public Task<Dictionary<string, object>> QueryD1Async(string databaseId, string sql, CancellationToken ct = default)
    {
        return Task.FromResult(new Dictionary<string, object> { ["results"] = Array.Empty<object>() });
    }

    /// <summary>Mock implementation of ICloudflarePort.GetKvValueAsync</summary>
    public Task<string?> GetKvValueAsync(string namespaceId, string key, CancellationToken ct = default)
    {
        return Task.FromResult<string?>(null);
    }

    /// <summary>Mock implementation of ICloudflarePort.SetKvValueAsync</summary>
    public Task SetKvValueAsync(string namespaceId, string key, string value, CancellationToken ct = default)
    {
        return Task.CompletedTask;
    }

    /// <summary>Mock implementation of ICloudflarePort.ListKvKeysAsync</summary>
    public Task<List<string>> ListKvKeysAsync(string namespaceId, string? prefix = null, CancellationToken ct = default)
    {
        return Task.FromResult(new List<string>());
    }

    /// <summary>Mock implementation of ICloudflarePort.VerifyTurnstileTokenAsync</summary>
    public Task<Dictionary<string, object>> VerifyTurnstileTokenAsync(string token, string remoteIp, CancellationToken ct = default)
    {
        return Task.FromResult(new Dictionary<string, object> { ["success"] = true });
    }

    /// <summary>Mock implementation of ICloudflarePort.GetStreamVideoStatusAsync</summary>
    public Task<Dictionary<string, object>> GetStreamVideoStatusAsync(string videoId, CancellationToken ct = default)
    {
        return Task.FromResult(new Dictionary<string, object> { ["status"] = "ready", ["videoId"] = videoId });
    }

    /// <summary>Mock implementation of ICloudflarePort.ListStreamVideosAsync</summary>
    public Task<List<Dictionary<string, object>>> ListStreamVideosAsync(CancellationToken ct = default)
    {
        return Task.FromResult(new List<Dictionary<string, object>>());
    }
}
