// =============================================================================
// MockSwarmPort — Auto-generated Mock adapter for ISwarmPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockSwarmPort : ISwarmPort
{
    /// <summary>Mock implementation of ISwarmPort.CreateSwarmAsync</summary>
    public Task<StorageResult<SwarmDefinition>> CreateSwarmAsync(SwarmDefinition definition, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<SwarmDefinition>>(default!);
    }

    /// <summary>Mock implementation of ISwarmPort.UpdateSwarmAsync</summary>
    public Task<StorageResult<SwarmDefinition>> UpdateSwarmAsync(SwarmDefinition definition, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<SwarmDefinition>>(default!);
    }

    /// <summary>Mock implementation of ISwarmPort.DeleteSwarmAsync</summary>
    public Task<StorageResult<bool>> DeleteSwarmAsync(string swarmId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<bool>>(default!);
    }

    /// <summary>Mock implementation of ISwarmPort.GetSwarmAsync</summary>
    public Task<StorageResult<SwarmDefinition>> GetSwarmAsync(string swarmId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<SwarmDefinition>>(default!);
    }

    /// <summary>Mock implementation of ISwarmPort.ListSwarmsAsync</summary>
    public Task<StorageResult<List<SwarmDefinition>>> ListSwarmsAsync(CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<SwarmDefinition>>>(default!);
    }

    /// <summary>Mock implementation of ISwarmPort.RunTaskAsync</summary>
    public Task<StorageResult<SwarmTask>> RunTaskAsync(SwarmTask task, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<SwarmTask>>(default!);
    }

    /// <summary>Mock implementation of ISwarmPort.RunTaskStreamingAsync</summary>
    public Task<StorageResult<SwarmTask>> RunTaskStreamingAsync(SwarmTask task, Action<SwarmMessage>? onMessage, Action<SwarmHandoffRecord>? onHandoff, Action<SwarmToolCall>? onToolCall, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<SwarmTask>>(default!);
    }

    /// <summary>Mock implementation of ISwarmPort.CancelTaskAsync</summary>
    public Task<StorageResult<bool>> CancelTaskAsync(string taskId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<bool>>(default!);
    }

    /// <summary>Mock implementation of ISwarmPort.GetTaskAsync</summary>
    public Task<StorageResult<SwarmTask>> GetTaskAsync(string taskId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<SwarmTask>>(default!);
    }

    /// <summary>Mock implementation of ISwarmPort.ListTasksAsync</summary>
    public Task<StorageResult<List<SwarmTask>>> ListTasksAsync(string? swarmId, int limit, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<SwarmTask>>>(default!);
    }

    /// <summary>Mock implementation of ISwarmPort.GetRunSummaryAsync</summary>
    public Task<StorageResult<SwarmRunSummary>> GetRunSummaryAsync(string taskId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<SwarmRunSummary>>(default!);
    }

    /// <summary>Mock implementation of ISwarmPort.RegisterToolHandler</summary>
    public void RegisterToolHandler(string toolName, Func<string, CancellationToken, Task<string>> handler)
    {
        // TODO: Implement Mock-specific logic
    }

    /// <summary>Mock implementation of ISwarmPort.GetRegisteredToolHandlers</summary>
    public IReadOnlyList<string> GetRegisteredToolHandlers()
    {
        // TODO: Implement Mock-specific logic
        return default!;
    }

}
