// =============================================================================
// MockEvidencePort — Auto-generated Mock adapter for IEvidencePort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockEvidencePort : IEvidencePort
{
    /// <summary>Mock implementation of IEvidencePort.SubmitAsync</summary>
    public Task<StorageResult<EvidenceSubmission>> SubmitAsync(EvidenceSubmission submission, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<EvidenceSubmission>>(default!);
    }

    /// <summary>Mock implementation of IEvidencePort.GetByIdAsync</summary>
    public Task<StorageResult<EvidenceSubmission>> GetByIdAsync(string submissionId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<EvidenceSubmission>>(default!);
    }

    /// <summary>Mock implementation of IEvidencePort.GetByRequestIdAsync</summary>
    public Task<StorageResult<List<EvidenceSubmission>>> GetByRequestIdAsync(string requestId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<EvidenceSubmission>>>(default!);
    }

    /// <summary>Mock implementation of IEvidencePort.GetByUserIdAsync</summary>
    public Task<StorageResult<List<EvidenceSubmission>>> GetByUserIdAsync(string userId, SubmissionPhase? phase, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<EvidenceSubmission>>>(default!);
    }

    /// <summary>Mock implementation of IEvidencePort.QueryAsync</summary>
    public Task<StorageResult<List<EvidenceSubmission>>> QueryAsync(EvidenceQuery query, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<List<EvidenceSubmission>>>(default!);
    }

    /// <summary>Mock implementation of IEvidencePort.UpdateStatusAsync</summary>
    public Task<StorageResult<bool>> UpdateStatusAsync(string submissionId, SubmissionStatus status, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<bool>>(default!);
    }

    /// <summary>Mock implementation of IEvidencePort.AttachProcessingResultAsync</summary>
    public Task<StorageResult<bool>> AttachProcessingResultAsync(string submissionId, EvidenceProcessingResult result, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<StorageResult<bool>>(default!);
    }

    /// <summary>Mock implementation of IEvidencePort.VerifyIntegrityAsync</summary>
    public Task<bool> VerifyIntegrityAsync(string submissionId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

}
