// =============================================================================
// MockSensorFusionPort — Auto-generated Mock adapter for ISensorFusionPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockSensorFusionPort : ISensorFusionPort
{
    /// <summary>Mock implementation of ISensorFusionPort.RecordSensorReadingAsync</summary>
    public Task<SensorReading> RecordSensorReadingAsync(SensorReading reading, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<SensorReading>(default!);
    }

    /// <summary>Mock implementation of ISensorFusionPort.RecordAccelerometerAsync</summary>
    public Task<AccelerometerReading> RecordAccelerometerAsync(AccelerometerReading reading, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<AccelerometerReading>(default!);
    }

    /// <summary>Mock implementation of ISensorFusionPort.RecordAcousticEventAsync</summary>
    public Task<AcousticReading> RecordAcousticEventAsync(AcousticReading reading, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<AcousticReading>(default!);
    }

    /// <summary>Mock implementation of ISensorFusionPort.RecordWearableHealthAsync</summary>
    public Task<WearableHealthReading> RecordWearableHealthAsync(WearableHealthReading reading, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<WearableHealthReading>(default!);
    }

    /// <summary>Mock implementation of ISensorFusionPort.RecordVisualClassificationAsync</summary>
    public Task<VisualClassification> RecordVisualClassificationAsync(VisualClassification classification, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<VisualClassification>(default!);
    }

    /// <summary>Mock implementation of ISensorFusionPort.FuseSensorDataAsync</summary>
    public Task<IReadOnlyList<CompositeSensorEvent>> FuseSensorDataAsync(string userId, TimeSpan window, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<CompositeSensorEvent>>(default!);
    }

    /// <summary>Mock implementation of ISensorFusionPort.GetRecentReadingsAsync</summary>
    public Task<IReadOnlyList<SensorReading>> GetRecentReadingsAsync(string userId, SensorType? type, int limit, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<SensorReading>>(default!);
    }

    /// <summary>Mock implementation of ISensorFusionPort.GetActiveCompositeEventsAsync</summary>
    public Task<IReadOnlyList<CompositeSensorEvent>> GetActiveCompositeEventsAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyList<CompositeSensorEvent>>(default!);
    }

    /// <summary>Mock implementation of ISensorFusionPort.GetSensorStatusAsync</summary>
    public Task<IReadOnlyDictionary<SensorType, SensorStatus>> GetSensorStatusAsync(string userId, string deviceId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<IReadOnlyDictionary<SensorType, SensorStatus>>(default!);
    }

    /// <summary>Mock implementation of ISensorFusionPort.CalibrateSensorAsync</summary>
    public Task<bool> CalibrateSensorAsync(string userId, string deviceId, SensorType type, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

}
