// =============================================================================
// MockPhraseProgrammingPort — Auto-generated Mock adapter for IPhraseProgrammingPort
// =============================================================================
// Generated by TheWatch.Cli CodeGenerator at 2026-03-25 00:00:28 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen
// =============================================================================

using TheWatch.Shared.Domain.Ports;
using TheWatch.Shared.Domain.Models;
using TheWatch.Shared.Enums;

namespace TheWatch.Adapters.Mock;

public class MockPhraseProgrammingPort : IPhraseProgrammingPort
{
    /// <summary>Mock implementation of IPhraseProgrammingPort.GetPhrasesForUserAsync</summary>
    public Task<List<EmergencyPhrase>> GetPhrasesForUserAsync(string userId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<List<EmergencyPhrase>>(default!);
    }

    /// <summary>Mock implementation of IPhraseProgrammingPort.AddPhraseAsync</summary>
    public Task<EmergencyPhrase> AddPhraseAsync(EmergencyPhrase phrase, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<EmergencyPhrase>(default!);
    }

    /// <summary>Mock implementation of IPhraseProgrammingPort.UpdatePhraseAsync</summary>
    public Task<EmergencyPhrase> UpdatePhraseAsync(EmergencyPhrase phrase, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<EmergencyPhrase>(default!);
    }

    /// <summary>Mock implementation of IPhraseProgrammingPort.RemovePhraseAsync</summary>
    public Task<bool> RemovePhraseAsync(string phraseId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

    /// <summary>Mock implementation of IPhraseProgrammingPort.GetPhraseByIdAsync</summary>
    public Task<EmergencyPhrase?> GetPhraseByIdAsync(string phraseId, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<EmergencyPhrase?>(default!);
    }

    /// <summary>Mock implementation of IPhraseProgrammingPort.ValidatePhraseUniqueness</summary>
    public Task<bool> ValidatePhraseUniqueness(string userId, string phraseText, CancellationToken ct)
    {
        // TODO: Implement Mock-specific logic
        return Task.FromResult<bool>(default!);
    }

}
