// =============================================================================
// ServiceCollectionExtensions — Auto-generated DI registrations
// =============================================================================
// Generated by TheWatch.Cli CecilAssemblyScanner at 2026-03-25 00:05:10 UTC
// DO NOT EDIT — regenerate with: dotnet run --project TheWatch.Cli -- codegen di-wire
//
// Example:
//   services.AddTheWatchAdapters();  // registers all port→adapter bindings
//
// WAL: This file is regenerated from Cecil assembly scan results.
//      Any manual edits will be overwritten on next codegen run.
//      To add custom registrations, create a separate extension method.
// =============================================================================

using Microsoft.Extensions.DependencyInjection;
using TheWatch.Adapters.Mock;
using TheWatch.Shared.Domain.Ports;

namespace TheWatch.Adapters.Mock;

public static class ServiceCollectionExtensions
{
    /// <summary>
    /// Register all discovered port→adapter bindings as singletons.
    /// Auto-generated from Cecil scan of 54 implementations.
    /// </summary>
    public static IServiceCollection AddTheWatchAdapters(this IServiceCollection services)
    {
        // ── TheWatch.Adapters.Mock ──
        services.AddSingleton<IAlarmSystemPort, MockAlarmSystemPort>();
        services.AddSingleton<IAuditTrail, MockAuditTrail>();
        services.AddSingleton<IAuthPort, MockAuthPort>();
        services.AddSingleton<IAwsPort, MockAwsAdapter>();
        services.AddSingleton<IAzurePort, MockAzureAdapter>();
        services.AddSingleton<IBlobStoragePort, MockBlobStoragePort>();
        services.AddSingleton<IBuildOutputPort, MockBuildOutputPort>();
        // ctor(ILogger logger)
        services.AddSingleton<ICCTVPort, MockCCTVAdapter>();
        services.AddSingleton<ICloudflarePort, MockCloudflarePort>();
        services.AddSingleton<IContextRetrievalPort, MockContextRetrievalPort>();
        services.AddSingleton<IDevWorkPort, MockDevWorkPort>();
        services.AddSingleton<IEgressComputationPort, MockEgressComputationPort>();
        services.AddSingleton<IEmbeddingPort, MockEmbeddingPort>();
        services.AddSingleton<IEmergencyServicesPort, MockEmergencyServicesPort>();
        // ctor(ILogger logger)
        services.AddSingleton<IEscalationPort, MockEscalationAdapter>();
        services.AddSingleton<IEvidencePort, MockEvidencePort>();
        services.AddSingleton<IFeatureTrackingPort, MockFeatureTrackingPort>();
        services.AddSingleton<IFirestorePort, MockFirestoreAdapter>();
        services.AddSingleton<IGitHubPort, MockGitHubAdapter>();
        // ctor(ILogger logger)
        services.AddSingleton<IGuardReportPort, MockGuardReportAdapter>();
        // ctor(IEnumerable providers)
        services.AddSingleton<IInfrastructureHealthPort, InfrastructureHealthAggregator>();
        services.AddSingleton<IInfrastructureHealthProvider, MockInfrastructureHealthProvider>();
        // ctor(ILogger logger)
        services.AddSingleton<IIoTAlertPort, MockIoTAlertAdapter>();
        // ctor(ILogger logger, IIoTAlertPort alertPort)
        services.AddSingleton<IIoTWebhookPort, MockIoTWebhookAdapter>();
        // ctor(ILogger logger)
        services.AddSingleton<IMessageGuardrailsPort, MockMessageGuardrailsAdapter>();
        // ctor(ILogger logger)
        services.AddSingleton<INavigationPort, MockNavigationAdapter>();
        // ctor(ILogger logger)
        services.AddSingleton<INotificationRegistrationPort, MockNotificationRegistrationAdapter>();
        // ctor(ILogger logger)
        services.AddSingleton<INotificationSendPort, MockNotificationSendAdapter>();
        // ctor(ILogger logger)
        services.AddSingleton<INotificationTrackingPort, MockNotificationTrackingAdapter>();
        services.AddSingleton<IOraclePort, MockOraclePort>();
        // ctor(ILogger logger)
        services.AddSingleton<IParticipationPort, MockParticipationAdapter>();
        services.AddSingleton<IPersonCapabilityPort, MockPersonCapabilityPort>();
        services.AddSingleton<IPhraseDetectionPort, MockPhraseDetectionPort>();
        services.AddSingleton<IPhraseMatchingEngine, MockPhraseMatchingEngine>();
        services.AddSingleton<IPhraseProgrammingPort, MockPhraseProgrammingPort>();
        services.AddSingleton<IQuickTapConfigurationPort, MockQuickTapConfigurationPort>();
        services.AddSingleton<IQuickTapEventPort, MockQuickTapEventPort>();
        // ctor(IMessageGuardrailsPort guardrails, IResponseTrackingPort trackingPort, ILogger logger)
        services.AddSingleton<IResponderCommunicationPort, MockResponderCommunicationAdapter>();
        // ctor(ILogger logger)
        services.AddSingleton<IResponseDispatchPort, MockResponseDispatchAdapter>();
        // ctor(ILogger logger)
        services.AddSingleton<IResponseRequestPort, MockResponseRequestAdapter>();
        // ctor(ILogger logger)
        services.AddSingleton<IResponseTrackingPort, MockResponseTrackingAdapter>();
        // ctor(ILogger logger)
        services.AddSingleton<ISceneNarrationPort, MockSceneNarrationAdapter>();
        services.AddSingleton<ISensorFusionPort, MockSensorFusionPort>();
        // ctor(ILogger logger)
        services.AddSingleton<ISmsPort, MockSmsAdapter>();
        services.AddSingleton<ISpatialIndex, MockSpatialIndex>();
        services.AddSingleton<IStorageService, MockStorageService>();
        services.AddSingleton<IStructurePort, MockStructurePort>();
        services.AddSingleton<ISurveyPort, MockSurveyPort>();
        services.AddSingleton<ISwarmInventoryPort, MockSwarmInventoryPort>();
        services.AddSingleton<ISwarmPort, MockSwarmPort>();
        services.AddSingleton<ITelephonyPort, MockTelephonyPort>();
        services.AddSingleton<IThreatTrackingPort, MockThreatTrackingPort>();
        services.AddSingleton<IVectorSearchPort, MockVectorSearchPort>();
        // ctor(ILogger logger)
        services.AddSingleton<IWatchCallPort, MockWatchCallAdapter>();

        return services;
    }
}
