// =============================================================================
// SosBypassTokenService — Short-lived HMAC tokens for emergency SOS access.
// =============================================================================
// Life-safety requirement: SOS triggers must work even when the user's auth
// token (Firebase/Entra ID) is expired. This service issues and validates
// lightweight HMAC-SHA256 tokens that mobile apps pre-cache.
//
// Token format: base64(uid:expiry_unix):base64(hmac_sha256(uid:expiry_unix, key))
// Default TTL: 24 hours (configurable via SosBypass:TokenLifetimeHours)
//
// Flow:
//   1. Authenticated user calls POST /api/response/sos-token → gets a bypass token
//   2. Mobile app caches the token locally (survives app restart)
//   3. During SOS with expired auth, app sends X-SOS-Bypass-Token header
//   4. ResponseController.TriggerResponse accepts either full auth OR bypass token
//
// Example:
//   var token = sosBypassService.GenerateToken("user-123");
//   var (valid, uid) = sosBypassService.ValidateToken(token);
//
// WAL: [WAL-SOS-BYPASS] prefix for all log messages.
// =============================================================================

using System.Security.Cryptography;
using System.Text;

namespace TheWatch.Dashboard.Api.Auth;

public class SosBypassTokenService
{
    private readonly byte[] _key;
    private readonly int _lifetimeHours;
    private readonly ILogger<SosBypassTokenService> _logger;

    public SosBypassTokenService(IConfiguration configuration, ILogger<SosBypassTokenService> logger)
    {
        _logger = logger;
        _lifetimeHours = configuration.GetValue("SosBypass:TokenLifetimeHours", 24);

        // Key from config or generate a stable one from the app's data protection key
        var configKey = configuration["SosBypass:HmacKey"];
        if (!string.IsNullOrEmpty(configKey))
        {
            _key = Convert.FromBase64String(configKey);
        }
        else
        {
            // Derive from machine-specific secret — stable across restarts
            using var sha = SHA256.Create();
            _key = sha.ComputeHash(Encoding.UTF8.GetBytes(
                $"TheWatch-SOS-Bypass-{Environment.MachineName}-{AppContext.BaseDirectory}"));
        }
    }

    /// <summary>
    /// Generate a short-lived SOS bypass token for the given user.
    /// Mobile apps should cache this and refresh when authenticated.
    /// </summary>
    public string GenerateToken(string uid)
    {
        var expiry = DateTimeOffset.UtcNow.AddHours(_lifetimeHours).ToUnixTimeSeconds();
        var payload = $"{uid}:{expiry}";
        var payloadBytes = Encoding.UTF8.GetBytes(payload);

        using var hmac = new HMACSHA256(_key);
        var signature = hmac.ComputeHash(payloadBytes);

        var token = $"{Convert.ToBase64String(payloadBytes)}.{Convert.ToBase64String(signature)}";

        _logger.LogInformation("[WAL-SOS-BYPASS] Generated bypass token for {Uid}, expires {Expiry}",
            uid, DateTimeOffset.FromUnixTimeSeconds(expiry));

        return token;
    }

    /// <summary>
    /// Validate an SOS bypass token. Returns (true, uid) if valid and not expired.
    /// </summary>
    public (bool IsValid, string? Uid) ValidateToken(string token)
    {
        try
        {
            var parts = token.Split('.');
            if (parts.Length != 2)
                return (false, null);

            var payloadBytes = Convert.FromBase64String(parts[0]);
            var providedSignature = Convert.FromBase64String(parts[1]);

            // Verify HMAC
            using var hmac = new HMACSHA256(_key);
            var expectedSignature = hmac.ComputeHash(payloadBytes);

            if (!CryptographicOperations.FixedTimeEquals(expectedSignature, providedSignature))
            {
                _logger.LogWarning("[WAL-SOS-BYPASS] Invalid signature on bypass token");
                return (false, null);
            }

            // Parse payload
            var payload = Encoding.UTF8.GetString(payloadBytes);
            var colonIndex = payload.LastIndexOf(':');
            if (colonIndex < 0)
                return (false, null);

            var uid = payload[..colonIndex];
            var expiryStr = payload[(colonIndex + 1)..];

            if (!long.TryParse(expiryStr, out var expiryUnix))
                return (false, null);

            var expiry = DateTimeOffset.FromUnixTimeSeconds(expiryUnix);
            if (expiry < DateTimeOffset.UtcNow)
            {
                _logger.LogWarning("[WAL-SOS-BYPASS] Expired bypass token for {Uid} (expired {Expiry})",
                    uid, expiry);
                return (false, null);
            }

            _logger.LogInformation("[WAL-SOS-BYPASS] Valid bypass token for {Uid}", uid);
            return (true, uid);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "[WAL-SOS-BYPASS] Failed to parse bypass token");
            return (false, null);
        }
    }
}
