// SwarmToolDefinition — declares a function/tool that a swarm agent can invoke.
// Maps directly to Azure OpenAI's ChatCompletionsFunctionToolDefinition.
//
// Example:
//   new SwarmToolDefinition
//   {
//       Name = "get_nearby_responders",
//       Description = "Find volunteer responders within a radius of the user's location",
//       ParametersJson = """
//       {
//           "type": "object",
//           "properties": {
//               "latitude": { "type": "number" },
//               "longitude": { "type": "number" },
//               "radius_km": { "type": "number", "default": 5 }
//           },
//           "required": ["latitude", "longitude"]
//       }
//       """
//   }

namespace TheWatch.Shared.Domain.Models;

public class SwarmToolDefinition
{
    /// <summary>Function name (must match ^[a-zA-Z0-9_-]+$).</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Human-readable description shown to the LLM.</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>JSON Schema for the function's parameters (as a raw JSON string).</summary>
    public string ParametersJson { get; set; } = """{"type": "object", "properties": {}}""";

    /// <summary>
    /// If true, this tool is a handoff function generated by the swarm runtime.
    /// Users don't need to set this — the swarm port generates these from HandoffTargets.
    /// </summary>
    public bool IsHandoff { get; set; }

    /// <summary>Target agent ID if this is a handoff tool.</summary>
    public string? HandoffTargetAgentId { get; set; }

    /// <summary>Whether the tool requires user confirmation before execution.</summary>
    public bool RequiresConfirmation { get; set; }
}
