// VectorDocument — a chunk of content with its embedding vector, ready for vector storage.
// Represents anything that can be embedded and searched: code files, incident reports,
// survey responses, DevWork logs, feature descriptions, standards documents.
//
// The embedding float[] is generated by the IEmbeddingPort and stored by IVectorSearchPort.
// Each document carries metadata for filtering (namespace, source, tags) so vector search
// can be scoped to relevant subsets.
//
// Example:
//   new VectorDocument
//   {
//       Id = "doc-evidence-controller",
//       Namespace = "codebase",
//       Content = "public class EvidenceController : ControllerBase { ... }",
//       Embedding = new float[] { 0.12f, -0.34f, ... },  // 1024 dims for Voyage AI
//       Source = "TheWatch.Dashboard.Api/Controllers/EvidenceController.cs",
//       Tags = new() { "controller", "evidence", "api" },
//       Provider = EmbeddingProvider.VoyageAI,
//       Store = VectorStoreProvider.Qdrant
//   };

using TheWatch.Shared.Enums;

namespace TheWatch.Shared.Domain.Models;

public class VectorDocument
{
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>Logical namespace for scoping searches (e.g., "codebase", "incidents", "standards").</summary>
    public string Namespace { get; set; } = "default";

    /// <summary>The raw text content that was embedded.</summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>The embedding vector. Dimensionality depends on provider (1536/3072/768/1024).</summary>
    public float[] Embedding { get; set; } = Array.Empty<float>();

    /// <summary>Source identifier (file path, document ID, URL, etc.).</summary>
    public string? Source { get; set; }

    /// <summary>Chunk index if the document was split into multiple chunks.</summary>
    public int ChunkIndex { get; set; }

    /// <summary>Total number of chunks for this source document.</summary>
    public int TotalChunks { get; set; } = 1;

    /// <summary>Searchable tags for metadata filtering.</summary>
    public List<string> Tags { get; set; } = new();

    /// <summary>Free-form metadata for provider-specific features.</summary>
    public Dictionary<string, string> Metadata { get; set; } = new();

    /// <summary>Which embedding model generated this vector.</summary>
    public EmbeddingProvider Provider { get; set; }

    /// <summary>Which vector store this document is persisted in.</summary>
    public VectorStoreProvider Store { get; set; }

    /// <summary>Estimated token count of the content for billing/quota purposes.</summary>
    public int EstimatedTokens { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }
}
